spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8000/login/oauth2/code/{registrationId}"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: snack-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.Snack_BE.DTOs,com.Snack_BE.Model"

  # docker:
  #   compose:
  #     enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5430/snack_website
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8000

jwt:
  secret: ${SECRET_KEY}

momo:
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  # redirect-url: ${PUBLIC_LINK}/public/api/payment/momo/return
  redirect-url: ${CLIENT_LINK}
  ipn-url: ${PUBLIC_LINK}/public/api/payment/momo/ipn
  partner-code: ${PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
